name: Test Packages

on:
  push:
    branches: [main, monorepo/frontend-frameworks]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests in all packages
        run: |
          yarn workspace @lingua/core test
          yarn workspace reactjs test
          yarn workspace sveltejs test
          yarn workspace vuejs test
